CREATE TABLE IF NOT EXISTS registrations (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    event_id INT NOT NULL,
    seats INTEGER NOT NULL DEFAULT 1 CHECK (seats > 0),
    registered_at date NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

ALTER TABLE registrations
    ADD COLUMN IF NOT EXISTS seats INTEGER NOT NULL DEFAULT 1 CHECK (seats > 0);
